function:
  detect: true
  admin-broadcast: true

message:
  broadcast:
    admin:
      - '&2[&dKeywordBlock&2] &9%player_name% &btry to send blocked word &c%player_message%'
  warn:
    player:
      - '&2[&dKeywordBlock&2] &c%player_message% include blocked word'
      - '&2[&dKeywordBlock&2] &cDo not try to send blocked word'

words:
