name: KeywordBlock
main: com.github.hank9999.KeywordBlock.KeywordBlock
version: 1.3
author: hank9999

permissions:
  KeywordBlock.admin:
    description: KeywordBlock Admin Perm
    default: op

commands:
  keywordblock:
    description: KeywordBlock Main Command