name: KeywordBlock
version: ${project.version}
main: com.github.hank9999.keywordblock.KeywordBlock
authors: [hank9999]
description: Block keyword in your server!

permissions:
  KeywordBlock.admin:
    description: KeywordBlock Admin Perm
    default: op

commands:
  keywordblock:
    description: KeywordBlock Main Command